spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create    # application 실행 시점에 테이블을 drop 하고, 다시 생성하는 것.
    properties:
      hibernate:
#        show_sql: true   (운영 환경에서는 System.out 을 통해서 로그를 찍으면 안됨 )
        format_sql: true

  # spring-boot-devtools 안될 때 추가
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: true

logging:
  level:
    org.hibernate.SQL: debug    # 로거를 통해서 로그를 찍어야 함.
    org.hibernate.type: trace